services:
  # Frontend service - static site
  - type: web
    name: neighbourhood-pro-finder-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          name: neighbourhood-pro-finder-backend
          type: web
          property: url

  # Backend service - FastAPI
  - type: web
    name: neighbourhood-pro-finder-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: neighbourhood-pro-finder-db
          property: connectionString

# Database service
databases:
  - name: neighbourhood-pro-finder-db
    plan: starter
    databaseName: pro_finder
    user: pro_finder_user
