# Real providers extracted from dataset.json
real_providers = [
    {'name': 'V-Tech Auto Ltd', 'service_type': 'auto', 'neighborhood': 'reading', 'contact': '950-2888', 'rating': 4.6},
    {'name': 'Bosch Car Service - R.A. Engineering', 'service_type': 'auto', 'neighborhood': 'reading', 'contact': '957-1369', 'rating': 4.7},
    {'name': 'motorbike spraying', 'service_type': 'auto', 'neighborhood': 'reading', 'contact': '', 'rating': 5},
    {'name': 'Adenville Ltd', 'service_type': 'auto', 'neighborhood': 'reading', 'contact': '099-9225', 'rating': 4.2},
    {'name': 'Loxone UK', 'service_type': 'auto', 'neighborhood': 'reading', 'contact': '204-9930', 'rating': 4.6},
    {'name': '1st Blocked Drains - Blocked drain Reading, Berkshire', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '405-0136', 'rating': 5},
    {'name': 'First Call Heating & Plumbing Solutions Ltd', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '', 'rating': 3.5},
    {'name': 'Getplumb', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '958-8882', 'rating': 4.9},
    {'name': 'Berkshire Heat - Plumber, Heating Solution & Boiler Repair in Reading', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '246-5806', 'rating': 5},
    {'name': 'Plumbers 24hrs Ltd', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '321-4354', 'rating': 4.6},
    {'name': 'Reading Heating & Plumbing', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '950-4247', 'rating': 4.8},
    {'name': 'Grant & Stone Reading Plumbers Merchants', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '942-9499', 'rating': 5},
    {'name': 'A Southern Plumbing & Heating', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '502-9528', 'rating': 4},
    {'name': '999 Plumber Reading', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '911-3999', 'rating': 5},
    {'name': 'Plumber in Reading Company', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '321-7172', 'rating': 5},
    {'name': 'EL plumbing and heating 24/7 Emergency.', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '401-6081', 'rating': 5},
    {'name': 'VLC Plumbing', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '361-6445', 'rating': 5},
    {'name': 'Drain & Able - Blocked Drains Reading, Berkshire', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '957-6244', 'rating': 4.9},
    {'name': 'Silverline Plumbing', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '942-6595', 'rating': 5},
    {'name': 'Reading Heating Solutions Ltd - Plumbers Reading', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '228-0558', 'rating': 4.8},
    {'name': 'BoilerTech Plumbing & Heating', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '411-5001', 'rating': 4.9},
    {'name': 'Excel Plumbing Supplies', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '958-2114', 'rating': 5},
    {'name': 'Kma plumbing', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '022-1465', 'rating': 5},
    {'name': 'Turners Plumbing & Heating Ltd', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '934-5627', 'rating': 5},
    {'name': 'iPlumber', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '', 'rating': 5},
    {'name': 'K V Plumbing & Heating', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '849-5926', 'rating': 4.9},
    {'name': 'SMALL JOB PLUMBING COMPANY', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '396-3578', 'rating': 4.7},
    {'name': 'WSC Plumbing and Home Services Ltd', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '327-2414', 'rating': 5},
    {'name': 'JD Drains Ltd Reading Berkshire', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '380-0173', 'rating': 4.7},
    {'name': 'Lucas Plumbing & Heating Ltd', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '437-1679', 'rating': 4.5},
    {'name': 'Same Day Plumber Reading', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '449-2475', 'rating': 3.7},
    {'name': 'Drains & Mains Ltd', 'service_type': 'plumber', 'neighborhood': 'reading', 'contact': '035-9312', 'rating': 4.8},
    {'name': 'The Loft Conversion Company (Rdg)', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '945-3469', 'rating': 5},
    {'name': 'Local Mr Fix', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '337-4358', 'rating': 5},
    {'name': 'Tarmat UK', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '046-6442', 'rating': 4.3},
    {'name': 'Witchalls Fencing', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '888-3715', 'rating': 5},
    {'name': 'A1 Handyman Services Reading', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '558-1621', 'rating': 5},
    {'name': 'Ahandyman Reading.com', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '203-6769', 'rating': 5},
    {'name': 'Dan the Handyman', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '828-2112', 'rating': 5},
    {'name': 'Priority Handyman Services', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '011-2303', 'rating': 5},
    {'name': 'Wearings carpentry', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '001-9777', 'rating': 4.6},
    {'name': 'M Lewin - Decorating and Property Maintenance', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '793-1877', 'rating': 4.3},
    {'name': 'Stately Construction', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '937-2855', 'rating': 5},
    {'name': 'M Richmond Building & Carpentry Contractors', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '732-5899', 'rating': 5},
    {'name': 'Richard A Reed Carpentry Services', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '115-5684', 'rating': 5},
    {'name': 'Timpson', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '957-2315', 'rating': 3.7},
    {'name': 'Timpson', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '950-3421', 'rating': 4.2},
    {'name': 'DJ Property Maintenance', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '995-2235', 'rating': 5},
    {'name': 'Latch Carpentry', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '449-2926', 'rating': 4.9},
    {'name': 'pvc-u-fix', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '250-4548', 'rating': 5},
    {'name': 'Pools Plus', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '940-4221', 'rating': 4},
    {'name': 'Underwood Carpentry Services', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '434-5987', 'rating': 4},
    {'name': 'Roman Roofing & Building', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '321-3802', 'rating': 4},
    {'name': 'A Mills & Sons Decorating & Carpentry', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '404-6178', 'rating': 5},
    {'name': 'D N Cullen Carpenter & Joiner', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '943-1441', 'rating': 5},
    {'name': 'Shaw Construction and Supplies Ltd', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '143-0833', 'rating': 5},
    {'name': 'Sulhamstead Handyman', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '080-0206', 'rating': 5},
    {'name': 'Carpentry service', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '079-9605', 'rating': 5},
    {'name': 'Da Vinci Builders', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '857-4722', 'rating': 4.3},
    {'name': 'Timpson', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '941-6317', 'rating': 3.6},
    {'name': 'Brian Robins Carpentry Contractors', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '315-2272', 'rating': 4.9},
    {'name': 'Huws Gray Theale', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '932-3700', 'rating': 4.8},
    {'name': 'Blackstone roofing Ltd', 'service_type': 'handyman', 'neighborhood': 'reading', 'contact': '322-4494', 'rating': 4.8},
    {'name': 'Spirit Energy', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '951-4490', 'rating': 4.8},
    {'name': 'City Electrical Factors Ltd (CEF)', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '957-4695', 'rating': 4.8},
    {'name': 'Edmundson Electrical Ltd', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '957-1201', 'rating': 4},
    {'name': 'Redlec Electrical', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '600-5540', 'rating': 5},
    {'name': 'Urban Electrics', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '033-1081', 'rating': 5},
    {'name': 'Amptek Electrical services', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '405-4746', 'rating': 4.9},
    {'name': 'Caversham Electrical Limited', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '', 'rating': 4.7},
    {'name': 'JD Electrics', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '406-5057', 'rating': 4.9},
    {'name': 'Beckley Electrical', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '467-4152', 'rating': 5},
    {'name': 'BS ELECTRICAL', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '309-0173', 'rating': 4.3},
    {'name': 'Sparkshire Electrical', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '996-1384', 'rating': 5},
    {'name': 'Carter Electrical', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '967-7033', 'rating': 4.6},
    {'name': 'James Electrical Installation Services LTD', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '927-2900', 'rating': 5},
    {'name': 'PJC Electrical Services Limited', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '909-9377', 'rating': 4.9},
    {'name': 'MKR Electrical Services', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '194-7785', 'rating': 4.4},
    {'name': 'Westgate Electrical Services Ltd', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '937-1277', 'rating': 5},
    {'name': 'Forbury Electrical', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '907-5331', 'rating': 5},
    {'name': 'OJD Electrical Solutions Limited', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '473-8564', 'rating': 5},
    {'name': 'M&B Electrical', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '966-1898', 'rating': 4},
    {'name': 'Stanley Electrical Services', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '955-1535', 'rating': 5},
    {'name': 'BS ELECTRICAL', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '309-0173', 'rating': 5},
    {'name': 'Daton Electrical Services ltd.', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '956-7645', 'rating': 4.8},
    {'name': 'DJ Mace & Son (Electrical Contractors) Limited', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '988-8860', 'rating': 5},
    {'name': 'Oke Electrical Reading Mortimer Common', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '', 'rating': 5},
    {'name': 'Teescroft Electrical Ltd', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '103-5305', 'rating': 5},
    {'name': 'Cymerman Electrical Service. Reading.', 'service_type': 'electrician', 'neighborhood': 'reading', 'contact': '893-0859', 'rating': 5},
    {'name': 'Tilehurst Electrical Services', 'service_type': 'electrician', 'neighborhood': 'unknown', 'contact': '947-4318', 'rating': 5},
    {'name': 'RF Cox and Son Electrical Services Ltd', 'service_type': 'electrician', 'neighborhood': 'unknown', 'contact': '339-1072', 'rating': 4},
    {'name': 'Woven Wood', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '315-2122', 'rating': 3.6},
    {'name': 'Mini Digger & Driver Hire', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '047-0889', 'rating': 4.3},
    {'name': 'Wickes Reading', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '958-8288', 'rating': 3.6},
    {'name': 'Oxford Road Community Garden', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '961-3706', 'rating': 4.6},
    {'name': 'Nick Baldwin Garden Design', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '128-4377', 'rating': 5},
    {'name': 'Richfield Garden Centre', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '957-1234', 'rating': 4.2},
    {'name': 'Bohemian Landscaping', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '405-0165', 'rating': 5},
    {'name': 'Blue Fern Landscapes LTD', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '508-8150', 'rating': 5},
    {'name': 'TIDY GARDENS', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '463-2132', 'rating': 4.6},
    {'name': 'Beechwood Tree Care - Tree Surgery, Tree Removal & Hedge Trimming', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '940-6115', 'rating': 4.9},
    {'name': 'Wargrave Nursery Plant Centre', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '940-4160', 'rating': 4.8},
    {'name': 'A & A Landscape and Building', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '900-6359', 'rating': 5},
    {'name': 'Green Room Garden Design + Gardening', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '623-8779', 'rating': 5},
    {'name': 'Berkshire Garden Buildings', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '940-1104', 'rating': 4.7},
    {'name': 'Dream Gardens Limited', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '969-2757', 'rating': 4.5},
    {'name': 'Hazelwood tree care', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '394-8025', 'rating': 5},
    {'name': 'The Gardening Club at Hare Hatch', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '940-1600', 'rating': 4.3},
    {'name': 'Creative Landscape Co Ltd', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '934-1500', 'rating': 4.7},
    {'name': "Reed's Landscapes", 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '466-0403', 'rating': 5},
    {'name': 'ANB Trees & Grounds', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '929-1428', 'rating': 5},
    {'name': 'Landscaping WellDone', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '824-9887', 'rating': 5},
    {'name': 'Wellingtonia Landscaping', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '602-2447', 'rating': 5},
    {'name': 'Roots 2 Shoots Tree Care', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '033-6880', 'rating': 5},
    {'name': 'BMS Driveways', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '327-7375', 'rating': 5},
    {'name': 'Adventures with Flowers', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '748-4047', 'rating': 5},
    {'name': 'L&R Garden Maintenance Ltd', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '245-1802', 'rating': 5},
    {'name': 'R G Services (UK) Limited', 'service_type': 'gardener', 'neighborhood': 'reading', 'contact': '932-4220', 'rating': 3.7},
    {'name': 'WildWood Gardening Ltd.', 'service_type': 'gardener', 'neighborhood': 'wokingham', 'contact': '428-8070', 'rating': 4.8},
    {'name': 'Owen Thomas Garden Landscapes Ltd', 'service_type': 'gardener', 'neighborhood': 'wokingham', 'contact': '143-1695', 'rating': 5},
    {'name': 'Garden Angels', 'service_type': 'gardener', 'neighborhood': 'wokingham', 'contact': '706-3473', 'rating': 5},
    {'name': 'SCS Landscape Management', 'service_type': 'gardener', 'neighborhood': 'wokingham', 'contact': '977-2186', 'rating': 3.6},
    {'name': 'Green landscapes', 'service_type': 'gardener', 'neighborhood': 'wokingham', 'contact': '675-8998', 'rating': 5},
    {'name': 'Revvi Driveways - Landscaping and Block Paving Wokingham', 'service_type': 'gardener', 'neighborhood': 'wokingham', 'contact': '035-6450', 'rating': 5},
    {'name': 'Ideal Home Improvements', 'service_type': 'gardener', 'neighborhood': 'wokingham', 'contact': '285-6812', 'rating': 4.9},
    {'name': 'Smart and Handy', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '052-4472', 'rating': 5},
    {'name': 'Quinn brothers, painter & decorator, floor & wall tiling, handyman.', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '761-5155', 'rating': 5},
    {'name': 'The Reading Handyman', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '464-0326', 'rating': 3.7},
    {'name': 'Prospect Joinery and Handyman', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '952-3466', 'rating': 5},
    {'name': 'Handy Holloway handyman maintenance service in Reading and surrounding areas', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '820-6790', 'rating': 5},
    {'name': 'B-Handy Home Renovations', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '575-3172', 'rating': 5},
    {'name': 'Reading Handyman', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '278-5006', 'rating': 5},
    {'name': 'SKWorks Handyman Services', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '078-7928', 'rating': 5},
    {'name': 'NC Carpentry & Joinery', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '616-4410', 'rating': 5},
    {'name': 'Wise Roofing', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '164-5155', 'rating': 4.7},
    {'name': 'Rivar Sand and Gravel Hare Hatch', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '940-1890', 'rating': 4.3},
    {'name': 'Berks Handyman', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '555-2555', 'rating': 5},
    {'name': 'Grove Group - Construction, Electricals & Plumbing', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '568-4793', 'rating': 5},
    {'name': 'The Windsor Handyman', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '059-9350', 'rating': 4.9},
    {'name': 'Precise Painting', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '', 'rating': 5},
    {'name': 'Hire A Hubby Crowthorne', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '111-4664', 'rating': 5},
    {'name': 'Bearwoodbrown Handyman', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '678-4077', 'rating': 5},
    {'name': 'Finchampstead Carpenters', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '445-8280', 'rating': 5},
    {'name': 'RG Handyman Services & Property Maintenance', 'service_type': 'handyman', 'neighborhood': 'unknown', 'contact': '443-2335', 'rating': 4.9},
    {'name': 'Advanced Climate Technical Services LTD', 'service_type': 'hvac', 'neighborhood': 'unknown', 'contact': '987-4540', 'rating': 5},
    {'name': 'ProAir │ Air Conditioning & Ventilation', 'service_type': 'hvac', 'neighborhood': 'unknown', 'contact': '009-6300', 'rating': 4.6},
    {'name': 'Industrial Heating Solutions', 'service_type': 'hvac', 'neighborhood': 'unknown', 'contact': '996-8118', 'rating': 5},
    {'name': 'Air Conditioning Services', 'service_type': 'hvac', 'neighborhood': 'unknown', 'contact': '315-0270', 'rating': 5},
    {'name': 'Premier Heating Solutions', 'service_type': 'hvac', 'neighborhood': 'reading', 'contact': '152-7595', 'rating': 4.8},
    {'name': 'Aircopro', 'service_type': 'hvac', 'neighborhood': 'reading', 'contact': '998-7717', 'rating': 5},
    {'name': 'vicmiras gas engineer services ltd', 'service_type': 'hvac', 'neighborhood': 'reading', 'contact': '768-6616', 'rating': 5},
    {'name': 'Delta Air Conditioning Services (Reading) Ltd', 'service_type': 'hvac', 'neighborhood': 'reading', 'contact': '959-7606', 'rating': 4.9},
    {'name': 'Comfy Heating & Plumbing Ltd', 'service_type': 'hvac', 'neighborhood': 'reading', 'contact': '835-2905', 'rating': 5},
    {'name': 'Norton Air Conditioning Ltd', 'service_type': 'hvac', 'neighborhood': 'reading', 'contact': '933-3999', 'rating': 4.9},
    {'name': 'J&c gardening and pond maintenance', 'service_type': 'gardener', 'neighborhood': 'unknown', 'contact': '895-8114', 'rating': 5},
    {'name': 'Your Local Gardeners (Reading)', 'service_type': 'gardener', 'neighborhood': 'unknown', 'contact': '', 'rating': 5},
    {'name': 'Drews Gardening & Landscaping', 'service_type': 'gardener', 'neighborhood': 'unknown', 'contact': '796-3102', 'rating': 4.9},
    {'name': 'Airtech Premier Ltd', 'service_type': 'hvac', 'neighborhood': 'crowthorne', 'contact': '478-0274', 'rating': 5},
    {'name': 'Apex Plumber Ltd Plumbing & Heating', 'service_type': 'hvac', 'neighborhood': 'crowthorne', 'contact': '529-5550', 'rating': 5},
    {'name': 'DMS Window Cleaning Services', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '996-0227', 'rating': 5},
    {'name': 'Blast Away', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '959-3000', 'rating': 5},
    {'name': "Bobby's Dry Cleaning&Loundry", 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '950-8989', 'rating': 4.7},
    {'name': 'Mariferrari cleaner service ltda', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '540-5105', 'rating': 5},
    {'name': 'Clean Club', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '298-9786', 'rating': 5},
    {'name': 'End of tenancy cleaning Reading', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '212-0419', 'rating': 4.8},
    {'name': 'RetroWife Cleaning Services', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '947-6102', 'rating': 5},
    {'name': 'JC Cleaning Services', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '942-4394', 'rating': 4.5},
    {'name': 'XTern Services', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '646-4411', 'rating': 5},
    {'name': 'Titan Cleaners', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '315-0069', 'rating': 4.3},
    {'name': 'Cleaning Bees', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '133-2323', 'rating': 5},
    {'name': 'Maidenhead Aquatics Hare Hatch', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '940-1122', 'rating': 4.6},
    {'name': 'Sakala Cleaning Service Reading', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '635-7851', 'rating': 4.8},
    {'name': 'The Little Cottage Cleaning Company', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '206-8015', 'rating': 4.7},
    {'name': 'Yes Yes Services ltd Cleaning', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '732-7043', 'rating': 5},
    {'name': 'Magic-Mop Cleaning and Ironing Services', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '280-2844', 'rating': 5},
    {'name': 'The Little Cottage', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '328-0110', 'rating': 4},
    {'name': 'Earley Cleaning Services', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '084-1294', 'rating': 4.9},
    {'name': 'Jetflow External Cleaning | Moss Removal & Pressure Jet Washing Berkshire', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '960-4596', 'rating': 5},
    {'name': 'CG Living - Eco Cleaners', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '437-0379', 'rating': 5},
    {'name': 'A&O Window Cleaning', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '470-8094', 'rating': 5},
    {'name': 'GK Services', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '229-4595', 'rating': 5},
    {'name': 'Thoroughs Cleaning', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '323-4591', 'rating': 5},
    {'name': 'Wedding Dress Cleaning Berkshire', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '052-0915', 'rating': 5},
    {'name': 'Peacock Carpet Cleaning Ltd', 'service_type': 'cleaner', 'neighborhood': 'reading', 'contact': '756-5009', 'rating': 5},
    {'name': 'Immaculate 23', 'service_type': 'cleaner', 'neighborhood': 'unknown', 'contact': '634-3872', 'rating': 5},
    {'name': 'Immaculate Cleaners', 'service_type': 'cleaner', 'neighborhood': 'unknown', 'contact': '255-9068', 'rating': 5},
    {'name': 'ALB Cleaning Services', 'service_type': 'cleaner', 'neighborhood': 'unknown', 'contact': '957-0683', 'rating': 5},
    {'name': 'JCL Exterior Cleaning', 'service_type': 'cleaner', 'neighborhood': 'unknown', 'contact': '449-2487', 'rating': 5},
    {'name': "Kibona's Cleaning services", 'service_type': 'cleaner', 'neighborhood': 'unknown', 'contact': '989-4046', 'rating': 5},
    {'name': 'Cleanhome Wokingham', 'service_type': 'cleaner', 'neighborhood': 'unknown', 'contact': '846-1019', 'rating': 4.9},
    {'name': 'Ovenu Newbury - Oven Cleaning Specialists', 'service_type': 'cleaner', 'neighborhood': 'unknown', 'contact': '582-6937', 'rating': 5},
    {'name': 'Tilehurst Carpet & Upholstery Cleaning', 'service_type': 'cleaner', 'neighborhood': 'unknown', 'contact': '095-4048', 'rating': 5},
    {'name': 'Dina Cleaning Services', 'service_type': 'cleaner', 'neighborhood': 'unknown', 'contact': '451-2980', 'rating': 4.8},
    {'name': 'Bonds of Berkshire I Exterior Cleaning Services', 'service_type': 'cleaner', 'neighborhood': 'unknown', 'contact': '973-2014', 'rating': 5},
    {'name': 'Hero clean Limited', 'service_type': 'cleaner', 'neighborhood': 'unknown', 'contact': '538-8325', 'rating': 5},
    {'name': 'Economy Locks', 'service_type': 'locksmith', 'neighborhood': 'reading', 'contact': '967-1474', 'rating': 4.6},
    {'name': 'Popalock Locksmith - By Norman Mansell, M.B.E.', 'service_type': 'locksmith', 'neighborhood': 'reading', 'contact': '440-5997', 'rating': 5},
    {'name': 'Fontecnobm| Reading Car key Replacement| Auto Locksmith', 'service_type': 'locksmith', 'neighborhood': 'reading', 'contact': '417-3508', 'rating': 5},
    {'name': 'Timpson Locksmiths and Safe Engineers', 'service_type': 'locksmith', 'neighborhood': 'reading', 'contact': '018-7187', 'rating': 3.8},
    {'name': 'Abbey Gate Locksmiths & Security Engineers Ltd', 'service_type': 'locksmith', 'neighborhood': 'reading', 'contact': '996-5274', 'rating': 4.9},
    {'name': 'Berkshire Expert Locksmiths', 'service_type': 'locksmith', 'neighborhood': 'reading', 'contact': '449-2441', 'rating': 4.8},
    {'name': 'ASAP Locksmiths', 'service_type': 'locksmith', 'neighborhood': 'reading', 'contact': '926-8641', 'rating': 4.8},
    {'name': 'Timpson Mobile Locksmiths', 'service_type': 'locksmith', 'neighborhood': 'reading', 'contact': '018-7187', 'rating': 4.9},
    {'name': 'Autolocks3000', 'service_type': 'locksmith', 'neighborhood': 'reading', 'contact': '059-7295', 'rating': 5},
    {'name': 'A1 Locksmiths (Berkshire) Ltd', 'service_type': 'locksmith', 'neighborhood': 'reading', 'contact': '939-1000', 'rating': 4.8},
    {'name': 'Lock Solutions in Wokingham, Caversham + Woodley', 'service_type': 'locksmith', 'neighborhood': 'reading', 'contact': '336-0177', 'rating': 5},
    {'name': 'Link Locksmith Services', 'service_type': 'locksmith', 'neighborhood': 'reading', 'contact': '910-9990', 'rating': 5},
    {'name': 'MYT KEY Locksmith', 'service_type': 'locksmith', 'neighborhood': 'reading', 'contact': '', 'rating': 5},
    {'name': 'Keytek Locksmiths Theale', 'service_type': 'locksmith', 'neighborhood': 'reading', 'contact': '214-1332', 'rating': 4.9},
    {'name': 'Space Locksmiths - Reading', 'service_type': 'locksmith', 'neighborhood': 'unknown', 'contact': '133-3232', 'rating': 5},
    {'name': '24-7 Car Keys Reading - Auto Locksmith', 'service_type': 'locksmith', 'neighborhood': 'unknown', 'contact': '055-5555', 'rating': 4.8},
    {'name': 'Lock Solutions - Locksmith Reading', 'service_type': 'locksmith', 'neighborhood': 'unknown', 'contact': '991-9951', 'rating': 5},
    {'name': 'LockFit Reading Locksmiths', 'service_type': 'locksmith', 'neighborhood': 'unknown', 'contact': '380-1061', 'rating': 5},
    {'name': 'Lockforce Locksmith Reading', 'service_type': 'locksmith', 'neighborhood': 'unknown', 'contact': '430-0152', 'rating': 5},
    {'name': 'Lock Solutions Bracknell', 'service_type': 'locksmith', 'neighborhood': 'unknown', 'contact': '456-8388', 'rating': 5},
    {'name': 'ProSafe Locksmiths', 'service_type': 'locksmith', 'neighborhood': 'unknown', 'contact': '144-4882', 'rating': 5},
    {'name': 'Keytek Locksmiths Reading', 'service_type': 'locksmith', 'neighborhood': 'unknown', 'contact': '907-3068', 'rating': 4.9},
    {'name': 'J Craythorne Electrical', 'service_type': 'electrician', 'neighborhood': 'maidenhead', 'contact': '830-2074', 'rating': 5},
    {'name': 'Admirable Electrics', 'service_type': 'electrician', 'neighborhood': 'maidenhead', 'contact': '169-9582', 'rating': 4.5},
    {'name': 'Maidenhead Electrical Ltd', 'service_type': 'electrician', 'neighborhood': 'maidenhead', 'contact': '830-1188', 'rating': 5},
    {'name': 'Dexter Electrical Services', 'service_type': 'electrician', 'neighborhood': 'bracknell', 'contact': '457-8827', 'rating': 4.9},
    {'name': 'Effect Electrical Ltd', 'service_type': 'electrician', 'neighborhood': 'bracknell', 'contact': '367-1321', 'rating': 5},
    {'name': 'Absolute Plumbing & Electrical', 'service_type': 'plumber', 'neighborhood': 'maidenhead', 'contact': '826-0087', 'rating': 4.3},
    {'name': 'Royal Flush Plumber Ltd', 'service_type': 'plumber', 'neighborhood': 'maidenhead', 'contact': '887-6191', 'rating': 4.9},
    {'name': 'Parsons Plumbing', 'service_type': 'plumber', 'neighborhood': 'unknown', 'contact': '656-5912', 'rating': 5},
    {'name': 'A-PLUMBER MAIDENHEAD (A DASH PLUMBER MAIDENHEAD)', 'service_type': 'plumber', 'neighborhood': 'unknown', 'contact': '926-8652', 'rating': 4.9},
    {'name': 'South Coast Plumbing', 'service_type': 'plumber', 'neighborhood': 'unknown', 'contact': '525-2374', 'rating': 5},
    {'name': 'Thermotec Plumbing and Heating', 'service_type': 'plumber', 'neighborhood': 'unknown', 'contact': '011-6944', 'rating': 5},
    {'name': 'Aquarius Plumbing and Heating', 'service_type': 'plumber', 'neighborhood': 'unknown', 'contact': '129-5673', 'rating': 5},
    {'name': 'The Lady Plumber', 'service_type': 'plumber', 'neighborhood': 'unknown', 'contact': '098-6357', 'rating': 5},
    {'name': 'SF Plumbing & Heating Services LTD', 'service_type': 'plumber', 'neighborhood': 'unknown', 'contact': '468-5678', 'rating': 5},
    {'name': 'MBA Plumbing and Gas services', 'service_type': 'plumber', 'neighborhood': 'unknown', 'contact': '061-3320', 'rating': 4.9},
    {'name': 'PP Heat Ltd t/a Precision Plumbing & Heating', 'service_type': 'plumber', 'neighborhood': 'unknown', 'contact': '988-8868', 'rating': 4.9},
    {'name': 'Poldan', 'service_type': 'handyman', 'neighborhood': 'slough', 'contact': '830-5979', 'rating': 5},
    {'name': 'Berkshire Handyman', 'service_type': 'handyman', 'neighborhood': 'slough', 'contact': '761-9396', 'rating': 5},
    {'name': 'Odd Job Handyman', 'service_type': 'handyman', 'neighborhood': 'windsor', 'contact': '107-0175', 'rating': 5},
    {'name': 'Anthony Paul Maintenance Ltd', 'service_type': 'handyman', 'neighborhood': 'maidenhead', 'contact': '854-0008', 'rating': 5},
    {'name': 'Carpenters Square', 'service_type': 'handyman', 'neighborhood': 'maidenhead', 'contact': '328-2958', 'rating': 5},
    {'name': 'Pure Electrical', 'service_type': 'electrician', 'neighborhood': 'wokingham', 'contact': '479-0368', 'rating': 5},
    {'name': 'Connex electrical', 'service_type': 'electrician', 'neighborhood': 'wokingham', 'contact': '614-5413', 'rating': 5},
    {'name': 'Baker Electrical Contractors', 'service_type': 'electrician', 'neighborhood': 'wokingham', 'contact': '973-4037', 'rating': 5},
    {'name': 'Copper Connexions Ltd', 'service_type': 'electrician', 'neighborhood': 'wokingham', 'contact': '767-1725', 'rating': 5},
    {'name': 'Matt Browning Ltd. Electrical Contractors', 'service_type': 'electrician', 'neighborhood': 'wokingham', 'contact': '497-0002', 'rating': 5},
    {'name': 'Green Electrical Services Ltd', 'service_type': 'electrician', 'neighborhood': 'wokingham', 'contact': '296-2432', 'rating': 5},
    {'name': 'CDE Solutions Ltd', 'service_type': 'electrician', 'neighborhood': 'wokingham', 'contact': '348-9428', 'rating': 5},
    {'name': 'SJW Plumbing and Heating', 'service_type': 'plumber', 'neighborhood': 'bracknell', 'contact': '297-6717', 'rating': 5},
    {'name': 'ReliableKey Locksmith Bracknell', 'service_type': 'locksmith', 'neighborhood': 'bracknell', 'contact': '460-9203', 'rating': 5},
    {'name': 'Through the Keyhole Locksmiths', 'service_type': 'locksmith', 'neighborhood': 'bracknell', 'contact': '591-6774', 'rating': 5},
    {'name': 'Adaptlocks', 'service_type': 'locksmith', 'neighborhood': 'bracknell', 'contact': '074-2847', 'rating': 5},
    {'name': 'Carpentry By Carters', 'service_type': 'handyman', 'neighborhood': 'bracknell', 'contact': '453-4035', 'rating': 4.8},
    {'name': 'DJM Carpentry', 'service_type': 'handyman', 'neighborhood': 'bracknell', 'contact': '974-9007', 'rating': 5},
    {'name': 'Billins Carpentry & Joinery', 'service_type': 'handyman', 'neighborhood': 'bracknell', 'contact': '492-2858', 'rating': 4.7},
    {'name': 'Berkshire Surrey Roofing Ltd', 'service_type': 'handyman', 'neighborhood': 'bracknell', 'contact': '799-9256', 'rating': 5},
    {'name': 'Fix-It Frankel', 'service_type': 'handyman', 'neighborhood': 'bracknell', 'contact': '234-7023', 'rating': 4.9},
    {'name': 'Cooltech Building Services Ltd', 'service_type': 'hvac', 'neighborhood': 'windsor', 'contact': '386-8117', 'rating': 5},
    {'name': 'ATD Electrical and Heating Services', 'service_type': 'hvac', 'neighborhood': 'maidenhead', 'contact': '836-9247', 'rating': 5},
    {'name': 'Air Intelligence Ltd', 'service_type': 'hvac', 'neighborhood': 'maidenhead', 'contact': '894-7937', 'rating': 5},
    {'name': 'Mansur Carpentry', 'service_type': 'handyman', 'neighborhood': 'wokingham', 'contact': '351-8059', 'rating': 5},
    {'name': 'Kennedy roofing and building Ltd', 'service_type': 'handyman', 'neighborhood': 'wokingham', 'contact': '290-0071', 'rating': 5},
    {'name': 'Rose Carpentry', 'service_type': 'handyman', 'neighborhood': 'wokingham', 'contact': '599-4126', 'rating': 5},
    {'name': 'QTD Ltd', 'service_type': 'handyman', 'neighborhood': 'wokingham', 'contact': '932-8596', 'rating': 4.5},
    {'name': 'Molly Maid in Maidenhead & Marlow', 'service_type': 'cleaner', 'neighborhood': 'maidenhead', 'contact': '800-1858', 'rating': 4.1},
    {'name': 'Berkshire Cleaning LTD', 'service_type': 'cleaner', 'neighborhood': 'maidenhead', 'contact': '833-4480', 'rating': 4.4},
    {'name': 'Bonny Professional Cleaners', 'service_type': 'cleaner', 'neighborhood': 'maidenhead', 'contact': '210-6922', 'rating': 4.8},
    {'name': 'HP Domestic & Lifestyle', 'service_type': 'cleaner', 'neighborhood': 'maidenhead', 'contact': '828-1122', 'rating': 5},
    {'name': 'Marlow Roofing Company', 'service_type': 'cleaner', 'neighborhood': 'maidenhead', 'contact': '111-5099', 'rating': 5},
    {'name': 'GCD Locksmiths', 'service_type': 'locksmith', 'neighborhood': 'maidenhead', 'contact': '890-2123', 'rating': 4.8},
    {'name': 'Zenith Locksmith Maidenhead', 'service_type': 'locksmith', 'neighborhood': 'maidenhead', 'contact': '830-2158', 'rating': 5},
    {'name': 'Featherduster Cleaners Ltd', 'service_type': 'cleaner', 'neighborhood': 'bracknell', 'contact': '430-0416', 'rating': 4.7},
    {'name': '101 Locksmiths', 'service_type': 'locksmith', 'neighborhood': 'wokingham', 'contact': '208-9302', 'rating': 5},
    {'name': 'Lockrite Security Ltd', 'service_type': 'locksmith', 'neighborhood': 'wokingham', 'contact': '978-3381', 'rating': 3.8},
    {'name': 'Apple Clean', 'service_type': 'cleaner', 'neighborhood': 'wokingham', 'contact': '587-4571', 'rating': 5},
    {'name': 'Ace Cleaning Domestic Ltd', 'service_type': 'cleaner', 'neighborhood': 'wokingham', 'contact': '979-4830', 'rating': 4.4},
    {'name': 'Snappyclean - End of Tenancy, Deep Cleaning & After Builders', 'service_type': 'cleaner', 'neighborhood': 'windsor', 'contact': '100-0698', 'rating': 4.8},
    {'name': 'Omega Group', 'service_type': 'hvac', 'neighborhood': 'slough', 'contact': '841-7184', 'rating': 4.8},
    {'name': 'The Berkshire Gardener', 'service_type': 'gardener', 'neighborhood': 'bracknell', 'contact': '', 'rating': 5},
    {'name': 'RG Plumbing & Heating', 'service_type': 'plumber', 'neighborhood': 'wokingham', 'contact': '250-0981', 'rating': 5},
    {'name': 'LB Plumbing & Heating', 'service_type': 'plumber', 'neighborhood': 'wokingham', 'contact': '345-4831', 'rating': 5},
    {'name': 'Eddie Plumbing Services', 'service_type': 'plumber', 'neighborhood': 'wokingham', 'contact': '955-6065', 'rating': 4.9},
    {'name': 'Gleeson Carpentry', 'service_type': 'handyman', 'neighborhood': 'shinfield', 'contact': '969-6571', 'rating': 4},
    {'name': 'Joseph & Spencer Design, Carpentry & Construction', 'service_type': 'handyman', 'neighborhood': 'sandhurst', 'contact': '424-0172', 'rating': 5},
    {'name': 'AK SMART Repairs', 'service_type': 'auto', 'neighborhood': 'wokingham', 'contact': '337-3565', 'rating': 4.8},
    {'name': 'C B Electrical Services', 'service_type': 'electrician', 'neighborhood': 'crowthorne', 'contact': '804-6614', 'rating': 5},
    {'name': 'Scott L P Electrical Services Ltd', 'service_type': 'electrician', 'neighborhood': 'crowthorne', 'contact': '521-0776', 'rating': 5},
    {'name': 'Crowthorne Electrical Services Ltd', 'service_type': 'electrician', 'neighborhood': 'crowthorne', 'contact': '662-6929', 'rating': 5},
    {'name': 'MasterKeyGuard Locksmith Crowthorne', 'service_type': 'locksmith', 'neighborhood': 'crowthorne', 'contact': '453-4143', 'rating': 4.7},
    {'name': 'Rolls Garden Services', 'service_type': 'gardener', 'neighborhood': 'crowthorne', 'contact': '554-3009', 'rating': 5},
    {'name': 'Top Notch Carpentry Ltd', 'service_type': 'handyman', 'neighborhood': 'newbury', 'contact': '467-4053', 'rating': 5},
    {'name': 'AJC Bespoke Carpentry', 'service_type': 'handyman', 'neighborhood': 'thatcham', 'contact': '693-8728', 'rating': 5},
    {'name': 'Local Glazier & Handyman', 'service_type': 'handyman', 'neighborhood': 'thatcham', 'contact': '586-0231', 'rating': 5},
]
